version: 0.

env:
  secrets-manager:
    GITHUB_TOKEN: github-token

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - echo Installing Go...
      - go version
  build:
    commands:
      - echo Running tests...
      - go test ./...
      - echo Building service...
      - mkdir -p bin
      - go build -o bin/service
artifacts:
  files:
    - bin/service

